export const shopCategories = [
  { value: "electronics", label: "Electronics" },
  { value: "fashion", label: "Fashion" },
  { value: "home", label: "Home & Garden" },
  { value: "toys", label: "Toys & Hobbies" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "automotive", label: "Automotive" },
  { value: "books", label: "Books" },
  { value: "groceries", label: "Groceries" },
  { value: "health", label: "Health & Beauty" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "pet", label: "Pet Supplies & Services" },
  { value: "medical", label: "Medical & Pharmacy" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "florist", label: "Florists & Gift Shops" },
  { value: "baby", label: "Baby & Kids Store" },
  { value: "art", label: "Art & Craft Supplies" },
  { value: "music", label: "Music Instruments & Stores" },
  { value: "technology", label: "Software & Technology Services" },
  { value: "garden", label: "Garden & Outdoor Equipment" },
  { value: "bakery", label: "Bakery & Confectionery" },
  { value: "optical", label: "Optical & EyeWear" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "realEstate", label: "Real Estate & Property Services" },
  { value: "fitness", label: "Fitness & Wellness Centers" },
  { value: "entertainment", label: "Entertainment & Gaming" },
  { value: "other", label: "Other" },
];
